# Generated by Django 4.0.3 on 2022-03-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life_giving', '0002_alter_raise_user_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raise_user',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to='document/'),
        ),
    ]
