# Generated by Django 4.0.3 on 2022-03-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('life_giving', '0003_alter_raise_user_doc_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donate_fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('email', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=25)),
                ('name_on_card', models.CharField(max_length=35)),
                ('card_number', models.IntegerField(max_length=16)),
                ('amount', models.IntegerField()),
                ('exp_year', models.IntegerField()),
                ('cvv', models.CharField(max_length=3)),
                ('donate_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='life_giving.raise_user')),
            ],
        ),
    ]
